production:
  adapter: mysql2
  encoding: utf8
  database: wedding
  pool: 5
  username: usr1
  password: toto
  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  database: wedding
  pool: 5
  username: usr1
  password: toto
  host: localhost
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: wedding_test
  pool: 5
  username: usr1
  password: toto
  host: localhost
  socket: /tmp/mysql.sock
